"""Generate the static bilingual page. All content remains readable without JavaScript."""
from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'scripts/content.json'
data=json.loads(SOURCE.read_text())
(ROOT/'scripts/content.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))
translations=json.loads((ROOT/'scripts/translations.json').read_text())
def t(en,zh):
    if en not in translations: raise ValueError(f'Missing translation: {en}')
    return f'<span class="en">{en}</span><span class="zh">{zh}</span><span class="ja">{translations[en]["ja"]}</span><span class="es">{translations[en]["es"]}</span>' 
def img(n,alt,hero=False):
    ratio='2572 / 1664' if n in [4,5,6] else '3600 / 2260'
    return f'<img data-image="{n}" src="assets/product/{n}-en-1280.webp" srcset="assets/product/{n}-en-640.webp 640w, assets/product/{n}-en-1280.webp 1280w, assets/product/{n}-en-1920.webp 1920w" sizes="(max-width: 700px) 94vw, 85vw" alt="{escape(alt)}" width="1920" height="{round(1920/(2572/1664 if n in [4,5,6] else 3600/2260))}" loading="{"eager" if hero else "lazy"}" decoding="async" {"fetchpriority=high" if hero else ""} style="aspect-ratio:{ratio}">'
store='https://apps.apple.com/app/id6760245734'
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f5f7fb"><meta name="description" content="Browse, compare and create with Domino Image Viewer for Mac. HDR, six-image comparison, pixel inspection and professional reviews."><meta name="robots" content="index, follow, max-image-preview:large"><meta name="google-site-verification" content="qyOjOzkDUlpCyftO7tnQvsLlXsDhNWgXO65EcRpPFRw"><meta name="baidu-site-verification" content="codeva-XblQrgUwwO"><link rel="canonical" href="https://kowanfkina.github.io/"><link rel="alternate" hreflang="x-default" href="https://kowanfkina.github.io/"><link rel="alternate" hreflang="en" href="https://kowanfkina.github.io/?lang=en"><link rel="alternate" hreflang="zh-CN" href="https://kowanfkina.github.io/?lang=zh"><link rel="alternate" hreflang="ja" href="https://kowanfkina.github.io/?lang=ja"><link rel="alternate" hreflang="es" href="https://kowanfkina.github.io/?lang=es"><meta property="og:type" content="website"><meta property="og:site_name" content="Domino Image Viewer"><meta property="og:title" content="Domino Image Viewer — Every detail matters."><meta property="og:description" content="One focused image workspace for Mac. Browse, compare, inspect and create."><meta property="og:url" content="https://kowanfkina.github.io/"><meta property="og:image" content="https://kowanfkina.github.io/assets/product/4-en-1280.webp"><meta name="twitter:card" content="summary_large_image"><title>Domino Image Viewer — Every detail matters.</title><link rel="icon" href="assets/product/icon.webp"><link rel="manifest" href="site.webmanifest"><script type="application/ld+json">{"@context":"https://schema.org","@type":"SoftwareApplication","name":"Domino Image Viewer","applicationCategory":"MultimediaApplication","operatingSystem":"macOS","description":"A professional image workspace for browsing, comparing, inspecting and creating on Mac.","url":"https://kowanfkina.github.io/","downloadUrl":"https://apps.apple.com/app/id6760245734","image":"https://kowanfkina.github.io/assets/product/4-en-1280.webp","offers":{"@type":"Offer","price":"0","priceCurrency":"USD"}}</script><script src="language.js"></script><link rel="stylesheet" href="styles.css"><script src="locale-data.js" defer></script><script src="app.js" defer></script></head><body>'''
html+=f'<a class="skip" href="#main">{t("Skip to content","跳转到正文")}</a><header class="nav"><div class="nav-inner"><a class="brand" href="#"><img src="assets/product/icon.webp" width="34" height="34" alt=""><span>Domino <b>Image Viewer</b></span></a><nav aria-label="Main"><a href="#compare">{t("Explore","探索功能")}</a><a href="#contact">{t("Support","支持")}</a><select id="language" aria-label="Language / 语言 / 言語 / Idioma"><option value="auto">Auto · 自动</option><option value="zh">简体中文</option><option value="en">English</option><option value="ja">日本語</option><option value="es">Español</option></select><a class="button small" href="{store}">{t("Get the app","获取 App")}</a></nav></div><div class="reading-progress"></div></header><main id="main">'
html+=f'''<section class="hero hero-v2" id="overview"><div class="hero-layout"><div class="hero-copy"><p class="hero-announcement"><i></i>{t('New HDR display','全新 HDR 显示')}</p><p class="eyebrow">DOMINO IMAGE VIEWER / MAC</p><h1>{t('See more.<br><em>Create better.</em>','不止看图。<br><em>看见更多可能。</em>')}</h1><p class="lead">{t('From your first favorite to the finest pixel. Browse, compare and create in one powerful Mac workspace.','从心仪的一张，到精细的每个像素。浏览、对比与创作，在一个专业 Mac 工作空间里完成。')}</p><div class="actions"><a class="button" href="{store}">{t('Discover on the App Store','前往 App Store')} ↗</a><a class="text-link" href="assets/product/film-en.mp4" data-film>{t('Watch the 30-second film','观看 30 秒演示')} <span class="play-icon">▶</span></a></div><div class="hero-specs"><div><strong>100+</strong><span>{t('image formats','种图片格式')}</span></div><div><strong>2–6</strong><span>{t('synchronized views','图同步对比')}</span></div><div><strong>HDR</strong><span>+ SDR</span></div></div></div><div class="hero-stage" data-parallax="hero"><div class="hero-aura"></div><div class="hero-window">{img(1,'Multi-image comparison workspace',True)}</div><div class="hero-mini"><div class="mini-title"><i></i>{t('Browse & organize','浏览与整理')}</div>{img(4,'Domino image browser, ratings and file tray',True)}</div><div class="hero-detail-badge"><span class="crosshair">⌖</span><div><strong>{t('One workspace. Every detail.','一个工作空间。每一处细节。')}</strong><small>RGB / HSV / ROI</small></div></div><div class="hero-view-switch" role="group" aria-label="Product preview"><button type="button" data-hero-view="1" aria-pressed="true">{t('Compare six images','六图同屏')}</button><button type="button" data-hero-view="4" aria-pressed="false">{t('Browse & organize','浏览与整理')}</button><button type="button" data-hero-view="9" aria-pressed="false">{t('Inspect every pixel','像素检视')}</button></div></div></div><p class="hero-foot"><span>↓</span>{t('Real app. Real possibilities.','真实应用界面，让可能性看得见。')}<span class="media-locale-note"> · {t('English interface demonstration','英文界面演示')}</span></p></section>'''
html+=f'''<section class="intro wrap" data-reveal><p class="eyebrow">{t('LESS SWITCHING. MORE CREATING.','少些切换，多些创作。')}</p><h2>{t('Your whole workflow.<br><span class="muted">Beautifully connected.</span>','完整工作流。<br><span class="muted">自然连在一起。</span>')}</h2><div class="intro-grid"><p>{t('From the first browse to the final review, keep your images and your tools together. Open mixed-format folders, find your favorites and move straight into the details.','从打开文件夹到完成最终评审，让图片与工具始终在一起。浏览多种格式，挑出心仪作品，随即深入细节。')}</p><div class="facts"><div><strong>100+</strong><span>{t('formats, including RAW','种格式，覆盖 RAW')}</span></div><div><strong>2–6</strong><span>{t('synchronized views','图同步对比')}</span></div><div><strong>HDR</strong><span>{t('a new way to see','全新显示模式')}</span></div></div></div></section>'''
html+=f'<section class="comparison" id="compare"><div class="compare-sticky"><div class="section-head wrap"><p class="eyebrow">{t("A CLOSER LOOK","越看，越清楚。")}</p><h2>{t("Great images. Meet great insight.","看见好画面。也看懂它。")}</h2></div><div class="comparison-shell wrap"><div class="compare-caption"><span class="chapter">01 — 03</span><h3 id="scene-title">Six images. One clear comparison.</h3><p id="scene-copy">Compare two to six images with synchronized zoom and pan.</p><div class="scene-tabs" role="tablist" aria-label="Comparison views">'
for i,(en,zh) in enumerate([('Six images','六图同屏'),('Difference','容差对比'),('Pixels','像素网格')]):
    html+=f'<button role="tab" id="tab-{i}" aria-controls="panel-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}" data-scene="{i}">{t(en,zh)}</button>'
html+='</div></div><div class="compare-screens">'
for i,n in enumerate([1,2,9]): html+=f'<div class="screen {"active" if i==0 else ""}" id="panel-{i}" role="tabpanel" aria-labelledby="tab-{i}" {"hidden" if i else ""}>{img(n,data[n-1]["en-US"]["screenLabel"])}</div>'
html+=f'</div></div><div class="scroll-hint">{t("Scroll to explore, or choose a view above","向下滚动探索，或点击切换视图")} <span>↓</span></div></div></section>'
html+=f'''<section class="motion-section wrap" data-reveal><div class="motion-copy"><p class="eyebrow">{t('IN SYNC. IN MOTION.','同步，才更从容。')}</p><h2>{t('Same detail.<br>Every view.','同一处细节。<br>每一张，都看清。')}</h2><p>{t('Zoom and pan together. Spend your time comparing images, not finding your place.','同步缩放与平移。把时间留给观察，不必在不同图片间反复定位。')}</p><button class="text-link" id="loop-toggle" type="button" aria-pressed="false">{t('Play demonstration ▶','播放操作演示 ▶')}</button></div><div class="loop-frame"><video id="compare-loop" muted loop playsinline preload="none" poster="assets/product/1-en-640.webp" aria-label="Synchronized image comparison demonstration"></video></div></section>'''
html+=f'''<section class="hdr" id="hdr"><div class="wrap"><div class="hdr-heading" data-reveal><p class="eyebrow">{t('A BRIGHTER PERSPECTIVE','换个视角，看见更多。')}</p><h2>{t('Let highlights<br><em>come to life.</em>','让高光，<br><em>更有层次。</em>')}</h2><p>{t('Meet HDR display. Switch between HDR and SDR, right inside your image workspace.','全新 HDR 显示。在熟悉的工作空间里，自由切换 HDR 与 SDR。')}</p></div><div class="hdr-frame" data-parallax="hdr">{img(3,'HDR and SDR display comparison')}</div><div class="hdr-bottom"><span>HDR <span class="muted">/</span> SDR</span><p>{t('HDR appearance depends on the image and display. This web preview is a standard dynamic range capture.','HDR 效果取决于源图像与显示设备。本页使用标准动态范围截图。')}</p></div></div></section>'''
html+=f'<section class="toolbox wrap" id="highlights"><div class="section-head" data-reveal><p class="eyebrow">{t("THOUGHTFULLY EQUIPPED","工具齐备，灵感就位。")}</p><h2>{t("Small details.<br>Big possibilities.","细节到位。<br>创作，自有空间。")}</h2><p>{t("Explore the tools that bring your image workflow together.","探索让图像工作流更完整的每一个工具。")}</p></div><div class="feature-grid">'
for n in [4,5,6,7,8,9,1,2,3]:
    d=data[n-1]
    html+=f'<article class="feature-card" data-reveal><a href="#detail-{n}" class="feature-open" data-detail="{n}"><div class="card-copy"><p class="eyebrow">{t(escape(d["en-US"]["label"]),escape(d["zh-Hans"]["label"]))}</p><h3>{t(" ".join(map(escape,d["en-US"]["title"])),"".join(map(escape,d["zh-Hans"]["title"])))}</h3></div><div class="card-image">{img(n,d["en-US"]["screenLabel"])}</div><span class="plus" aria-hidden="true">+</span><span class="sr-only">{t("Explore feature","查看功能详情")}</span></a></article>'
html+=f'</div></section><section class="closing wrap" data-reveal><img src="assets/product/icon.webp" alt="" width="88" height="88" loading="lazy"><h2>{t("Give your images<br>a space of their own.","给你的图片，<br>一个专属工作空间。")}</h2><p>{t("Domino Image Viewer. Made for your Mac.","Domino Image Viewer。为你的 Mac 打造。")}</p><a class="button" href="{store}">{t("View on the App Store","在 App Store 中查看")} ↗</a></section>'
html+=f'<section class="support wrap" id="contact"><div><h2>{t("Here to help.","随时为你提供帮助。")}</h2><p>{t("Questions, feedback or something not working? Get in touch.","使用疑问、功能建议，或遇到问题？欢迎联系。")}</p></div><div><a href="mailto:1134105470@qq.com">1134105470@qq.com ↗</a><a href="https://kowanfkina.github.io/Domino-Image-Viewer-Privacy-Policy/">{t("Privacy policy","隐私政策")} ↗</a></div></section><section class="fallback-details wrap" aria-label="Feature details">'
for n in range(1,10):
    d=data[n-1];html+=f'<details id="detail-{n}"><summary>{t(d["en-US"]["label"],d["zh-Hans"]["label"])}</summary><p>{t(d["en-US"]["description"],d["zh-Hans"]["description"])}</p></details>'
html+=f'</section></main><footer class="wrap"><span>© 2026 Domino Image Viewer</span><span>{t("Every detail matters.","每一处细节，都重要。")}</span><a href="#">{t("Back to top ↑","返回顶部 ↑")}</a></footer><dialog id="feature-dialog" aria-labelledby="detail-title"><button class="close" type="button" aria-label="Close">×</button><div class="dialog-content"></div></dialog><dialog id="film-dialog" aria-label="Product demonstration"><button class="close" type="button" aria-label="Close">×</button><video id="film" controls playsinline preload="none"></video><p>{t("Original music · Clear Motion","原创配乐 · Clear Motion")}<span class="media-locale-note"> · {t("English interface demonstration","英文界面演示")}</span></p></dialog></body></html>'
(ROOT/'index.html').write_text(html)
(ROOT/'feature-content.js').write_text('export default '+json.dumps(data,ensure_ascii=False)+';\n')
print('Built bilingual semantic page and lazy feature content.')
